### ISSUE TITLE
Does `PMMLModel.score()` ever return something other than a `Double`?

### ISSUE THREAD

**Issue by deanwampler** [lightbend/kafka-with-akka-streams-kafka-streams-tutorial#10]
It appears that it does, but there is this "out" at the end:

```
    // Prepare output
    result.get(tname) match {
      case c: Computable => c.getResult.toString.toDouble
      case v => v
    }
```
What "non-Computable" might be returned? Could we assume it's an error if the first case class fails to match, and through an exception? Doing so would mean that `Mode.score` could return `Double` and all the ugly casts to `Double` everywhere could be removed.

**Comment by blublinsky** [comment]
Yes, The model interface is generic and allows to return anything. Implementation is specific for the data and model used.

**Comment by deanwampler** [comment]
Makes sense. Should we force the interface to always return `Double` or `Option[Double]`, if necessary, for this project, to simplify the code that uses it?

**Comment by blublinsky** [comment]
I would not do that, not now
